<?php
// Code generated by MCHP Chatbot
require_once __DIR__ . '/auth.php';

// Redirect already logged-in users to their portal.
if (!empty($_SESSION['authenticated'])) {
    header('Location: ' . ($_SESSION['role'] === 'admin' ? '/admin/portal.php' : '/employee/portal.php'));
    exit;
}

// ... existing code ...
$error = $_GET['error'] ?? '';
$success = $_GET['success'] ?? '';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,500;0,9..144,600;1,9..144,500&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/css/tokens.css">
<link rel="stylesheet" href="assets/css/components/index.css">
</head>
<body>

<div id="view-login">
  <svg class="bg-lotus" viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg">
    <g fill="none" stroke="#D2A7A7" stroke-width="1.1">
      <path d="M400 620 C 300 560, 260 460, 300 380 C 340 460, 380 500, 400 620 Z"/>
      <path d="M400 620 C 500 560, 540 460, 500 380 C 460 460, 420 500, 400 620 Z"/>
      <path d="M400 620 C 340 520, 340 420, 400 340 C 460 420, 460 520, 400 620 Z"/>
      <path d="M400 620 C 260 540, 180 440, 200 320 C 300 380, 360 460, 400 620 Z"/>
      <path d="M400 620 C 540 540, 620 440, 600 320 C 500 380, 440 460, 400 620 Z"/>
      <circle cx="400" cy="360" r="14"/>
    </g>
    <g fill="none" stroke="#6C714F" stroke-width="1">
      <path d="M180 700 C 130 660, 120 610, 160 580 C 190 620, 200 650, 180 700 Z"/>
      <path d="M620 700 C 670 660, 680 610, 640 580 C 610 620, 600 650, 620 700 Z"/>
    </g>
  </svg>

  <div class="login-card">
    <div class="login-brand">
      <svg class="lotus-mark" viewBox="0 0 100 100" fill="none">
        <path d="M50 78 C 38 68 32 54 38 42 C 44 54 48 60 50 78 Z" fill="#D2A7A7"/>
        <path d="M50 78 C 62 68 68 54 62 42 C 56 54 52 60 50 78 Z" fill="#D2A7A7" opacity="0.85"/>
        <path d="M50 78 C 42 62 42 46 50 34 C 58 46 58 62 50 78 Z" fill="#A18261"/>
        <path d="M50 78 C 30 66 20 48 24 30 C 40 40 46 54 50 78 Z" fill="#6D382B" opacity="0.8"/>
        <path d="M50 78 C 70 66 80 48 76 30 C 60 40 54 54 50 78 Z" fill="#6D382B" opacity="0.8"/>
        <circle cx="50" cy="40" r="4" fill="#6C714F"/>
      </svg>
      <h1>TAPP</h1>
      <p>Digital Attendance, in full bloom</p>
    </div>

    <?php if ($error === '1'): ?>
      <p style="background:rgba(109,56,43,0.25); color:#e6b2a4; padding:10px 14px; border-radius:9px; font-size:12.5px; margin-bottom:16px;">
        Please fill in every field and make sure passwords match.
      </p>
    <?php elseif ($error === '2'): ?>
      <p style="background:rgba(109,56,43,0.25); color:#e6b2a4; padding:10px 14px; border-radius:9px; font-size:12.5px; margin-bottom:16px;">
        That email or employee ID already exists. Please sign in or use a different identity.
      </p>
    <?php elseif ($error === '3'): ?>
      <p style="background:rgba(109,56,43,0.25); color:#e6b2a4; padding:10px 14px; border-radius:9px; font-size:12.5px; margin-bottom:16px;">
        We could not create your account right now. Please try again later.
      </p>
    <!-- admin-code error removed since admin code is no longer required -->
    <?php elseif ($success === '1'): ?>
      <p style="background:rgba(108,113,79,0.15); color:#D2A7A7; padding:10px 14px; border-radius:9px; font-size:12.5px; margin-bottom:16px;">
        Account created successfully. Please sign in.
      </p>
    <?php endif; ?>

    <form method="POST" action="signup_process.php" id="signup-form">
      <div class="field">
        <label>Full Name</label>
        <input name="name" type="text" placeholder="e.g. Sarah Lee">
      </div>
      <div class="field">
        <label>Employee ID</label>
        <input name="employee_id" type="text" placeholder="e.g. S-005">
      </div>
      <div class="field">
        <label>Email</label>
        <input name="email" type="email" placeholder="e.g. sarah.lee@tapp.co">
      </div>
      <!-- Admin code removed: users can now select role directly -->
      <input type="hidden" name="role" value="admin">
      <div class="field">
        <label>Password</label>
        <input name="password" type="password" placeholder="••••••••">
      </div>
      <div class="field">
        <label>Confirm Password</label>
        <input name="password_confirm" type="password" placeholder="••••••••">
      </div>
      <button type="submit" class="btn-primary">Create Account</button>
    </form>

    <p class="login-hint">Already have an account? <a href="login.php">Sign in</a></p>
  </div>
</div>

<script src="assets/js/app.js"></script>
</body>
</html>
