<?php

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../bootstrap/app.php';

use App\Database\Connection;

if ($argc < 2) {
    fwrite(
        STDERR,
        "Usage: php backend/cron/db_restore.php <backup-file.sql> [--dry-run]\n"
    );
    exit(1);
}

$backupPath = $argv[1];
$dryRun = in_array('--dry-run', $argv, true);

if (!is_file($backupPath)) {
    fwrite(
        STDERR,
        "Restore failed: backup file not found: {$backupPath}\n"
    );
    exit(1);
}

if (strtolower(pathinfo($backupPath, PATHINFO_EXTENSION)) !== 'sql') {
    fwrite(
        STDERR,
        "Restore failed: backup file must have a .sql extension.\n"
    );
    exit(1);
}

$sql = file_get_contents($backupPath);

if ($sql === false) {
    fwrite(
        STDERR,
        "Restore failed: unable to read backup file.\n"
    );
    exit(1);
}

/*
 * Only accept backups generated by our BackupService.
 */
if (!str_contains($sql, '-- TAPP Database Backup')) {
    fwrite(
        STDERR,
        "Restore failed: this does not appear to be a TAPP database backup.\n"
    );
    exit(1);
}

try {
    $statements = splitSqlStatements($sql);

    if ($statements === []) {
        throw new RuntimeException('Backup contains no SQL statements.');
    }

    $statistics = analyseStatements($statements);

    echo "Backup validation successful.\n";
    echo "Backup: {$backupPath}\n";
    echo "Statements: {$statistics['statements']}\n";
    echo "Tables: {$statistics['tables']}\n";
    echo "INSERT statements: {$statistics['inserts']}\n";
    echo "DROP TABLE statements: {$statistics['drops']}\n";
    echo "CREATE TABLE statements: {$statistics['creates']}\n";
    echo PHP_EOL;

    if ($dryRun) {
        echo "DRY RUN: no database changes were made.\n";
        exit(0);
    }

    $pdo = Connection::get();

    echo "WARNING: This will modify the configured database.\n";
    echo "Database: " . config('database.name') . "\n";
    echo PHP_EOL;
    echo "Type RESTORE to continue: ";

    $confirmation = trim(fgets(STDIN));

    if ($confirmation !== 'RESTORE') {
        echo "Restore cancelled.\n";
        exit(0);
    }

    echo PHP_EOL;
    echo "Starting restore...\n";

    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');

    try {
        foreach ($statements as $statement) {
            $pdo->exec($statement);
        }

        echo "Restore completed successfully.\n";
    } finally {
        /*
         * Always attempt to restore foreign-key checking,
         * even if one of the SQL statements fails.
         */
        $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
    }
} catch (Throwable $e) {
    fwrite(
        STDERR,
        "Restore failed: {$e->getMessage()}\n"
    );
    exit(1);
}

/**
 * Split SQL statements while respecting quoted strings,
 * quoted identifiers and SQL comments.
 *
 * This is intentionally designed for the SQL generated by
 * BackupService rather than being a complete MySQL SQL parser.
 *
 * @return string[]
 */
function splitSqlStatements(string $sql): array
{
    $statements = [];
    $current = '';

    $length = strlen($sql);

    $inSingleQuote = false;
    $inDoubleQuote = false;
    $inBacktick = false;
    $inLineComment = false;

    for ($i = 0; $i < $length; $i++) {
        $char = $sql[$i];
        $next = $i + 1 < $length ? $sql[$i + 1] : '';

        /*
         * Handle line comments.
         */
        if ($inLineComment) {
            if ($char === "\n" || $char === "\r") {
                $inLineComment = false;
                $current .= $char;
            }

            continue;
        }

        /*
         * Handle single-quoted strings.
         */
        if ($inSingleQuote) {
            $current .= $char;

            if ($char === '\\') {
                if ($i + 1 < $length) {
                    $current .= $sql[++$i];
                }

                continue;
            }

            if ($char === "'") {
                /*
                 * SQL allows two single quotes to represent one
                 * single quote inside a string.
                 */
                if ($next === "'") {
                    $current .= $sql[++$i];
                } else {
                    $inSingleQuote = false;
                }
            }

            continue;
        }

        /*
         * Handle double-quoted strings.
         */
        if ($inDoubleQuote) {
            $current .= $char;

            if ($char === '\\') {
                if ($i + 1 < $length) {
                    $current .= $sql[++$i];
                }

                continue;
            }

            if ($char === '"') {
                if ($next === '"') {
                    $current .= $sql[++$i];
                } else {
                    $inDoubleQuote = false;
                }
            }

            continue;
        }

        /*
         * Handle backtick-quoted identifiers.
         */
        if ($inBacktick) {
            $current .= $char;

            if ($char === '`') {
                if ($next === '`') {
                    $current .= $sql[++$i];
                } else {
                    $inBacktick = false;
                }
            }

            continue;
        }

        /*
         * Start a SQL line comment.
         */
        if ($char === '#' || ($char === '-' && $next === '-')) {
            $inLineComment = true;

            if ($char === '-' && $next === '-') {
                $i++;
            }

            continue;
        }

        /*
         * Start quoted strings/identifiers.
         */
        if ($char === "'") {
            $inSingleQuote = true;
            $current .= $char;
            continue;
        }

        if ($char === '"') {
            $inDoubleQuote = true;
            $current .= $char;
            continue;
        }

        if ($char === '`') {
            $inBacktick = true;
            $current .= $char;
            continue;
        }

        /*
         * A semicolon outside quotes/comments terminates
         * the SQL statement.
         */
        if ($char === ';') {
            $statement = trim($current);

            if ($statement !== '') {
                $statements[] = $statement;
            }

            $current = '';
            continue;
        }

        $current .= $char;
    }

    $remaining = trim($current);

    if ($remaining !== '') {
        $statements[] = $remaining;
    }

    return $statements;
}

/**
 * Analyse a generated backup without executing it.
 *
 * @param string[] $statements
 * @return array{
 *     statements:int,
 *     tables:int,
 *     inserts:int,
 *     drops:int,
 *     creates:int
 * }
 */
function analyseStatements(array $statements): array
{
    $tables = [];
    $inserts = 0;
    $drops = 0;
    $creates = 0;

    foreach ($statements as $statement) {
        $normalised = preg_replace('/\s+/', ' ', trim($statement));

        if (!is_string($normalised)) {
            continue;
        }

        if (preg_match(
            '/^DROP TABLE IF EXISTS `([^`]+)`/i',
            $normalised,
            $matches
        )) {
            $tables[$matches[1]] = true;
            $drops++;
            continue;
        }

        if (preg_match(
            '/^CREATE TABLE `([^`]+)`/i',
            $normalised,
            $matches
        )) {
            $tables[$matches[1]] = true;
            $creates++;
            continue;
        }

        if (preg_match('/^INSERT INTO `([^`]+)`/i', $normalised)) {
            $inserts++;
        }
    }

    return [
        'statements' => count($statements),
        'tables' => count($tables),
        'inserts' => $inserts,
        'drops' => $drops,
        'creates' => $creates,
    ];
}
