# COMPANY SETTINGS
COMPANY_NAME = "TAPP"

# DATABASE SETTINGS
DB_HOST = 
DB_PORT = 
DB_NAME = 
DB_USER = 
DB_PASSWORD = 

# RFID SETTINGS
# Reset Pin (GPIO)
RFID_RST_PIN = 25
# SPI Bus
SPI_BUS = 0
# SPI Device (CE0)
SPI_DEVICE = 0

# ATTENDANCE SETTINGS
# Prevent accidental double scans
COOLDOWN_MINUTES = 15
# Time format
TIME_FORMAT = "%H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

# LOGGING
LOG_FILE = "logs/attendance.log"


